### ISSUE TITLE
Where did the docker image ceph/demo go?

### ISSUE THREAD

**Issue by DeepDiver1975** [ceph/ceph-container#1169]
What happened:
We use the docker image ceph/demo within our ci setup.
As of yesterday it seems to be gone.

Where did it go? THX a lot

**Comment by leseb** [comment]
I'm sorry to read that @DeepDiver1975 -, I actually removed that image yesterday since it was not maintained anymore and did not receive any update for the last 10 months.

If you want to keep on using `ceph/demo`, you should switch to `ceph/daemon` and call it with `demo`, see an example run here: https://github.com/ceph/ceph-container/blob/master/.travis.yml#L23

Sorry for the inconvenience.

**Comment by DeepDiver1975** [comment]
@leseb thanks a lot for your feedback!

We are using the ceph images within a drone setup and I see the container hanging at the demo user creation:

````
2018-08-22 10:00:30  /entrypoint.sh: Setting up a demo user...
++demo.sh:129: bootstrap_demo_user(): '[' -n owncloud ']'
++demo.sh:129: bootstrap_demo_user(): '[' -n owncloud123456 ']'
++demo.sh:129: bootstrap_demo_user(): '[' -n secret123456 ']'
++demo.sh:130: bootstrap_demo_user(): radosgw-admin --cluster ceph user create --uid=owncloud '--display-name=Ceph demo user' --access-key=owncloud123456 --secret-key=secret123456

**Comment by DeepDiver1975** [comment]
This is the ceph container setup:

```yaml
  ceph:
    image: ceph/daemon:v3.0.5-stable-3.0-jewel-ubuntu-16.04-x86_64
    pull: true
    environment:
      - NETWORK_AUTO_DETECT=4
      - CEPH_DAEMON=demo
      - RGW_NAME=ceph
      - CEPH_DEMO_UID=owncloud
      - CEPH_DEMO_ACCESS_KEY=owncloud123456
      - CEPH_DEMO_SECRET_KEY=secret123456
      - DEBUG=verbose

**Comment by DeepDiver1975** [comment]
seems to be related to v3.0.5-stable-3.0-jewel-ubuntu-16.04-x86_64 - latest can create the user but fails later:

```
leseb-Sree-4ab9969/xmlparser.py
/sree /
/
/sree /
/
 * Running on http://0.0.0.0:5000/
demo.sh: line 269: ceph-rest-api: command not found
2018-08-22 10:11:30  /entrypoint.sh: SUCCESS
exec: PID 1177: spawning ceph --cluster ceph -w

**Comment by DeepDiver1975** [comment]
THX a lot! We can iterate from here!

**Comment by leseb** [comment]
@DeepDiver1975 Ok good to know!

**Comment by Goltergaul** [comment]
which port do i need to expose so that i can connect to the demo cluster?

**Comment by dsavineau** [comment]
@Goltergaul you should have open a dedicated issue for this instead of replying on a closed one.

To answer to your question, the simpler way if you don't want to manage the port list is to use the `--host=net` option.
If you want to use a different network container option, then it depends on the ceph daemons and how you configure them with the demo. By default:

- mon: 6879 (+3300 with nautilus)
- mds,mgr,osd: 6800-6811
- rgw: 8080
- rest api: 8003
- sree: 5000

**Comment by lijin543** [comment]
Hello, although you deleted the image that is no longer maintained, I can not find the old image on the web page, but I can still download "ceph/demo", why? This is the image I just downloaded
![image](https://user-images.githubusercontent.com/88606270/215708941-655401b0-b80f-450e-b84f-9f5ef190737e.png)

**Comment by hrchu** [comment]
The Ceph demo image is back again. As an seven year ceph user, not sure why they keep bothering with it without documenting any changelog. Additionally, they are unwilling to provide a stable demo image.
