### ISSUE TITLE
Can't use NVMe disks as OSDs.

### ISSUE THREAD

**Issue by jrobertsgb** [ceph/ceph-container#1253]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
When the daemon tries to mount an nvme mount, /dev/nvme0n1p1, it instead tries to mount /dev/nvme0n11.

What you expected to happen:
It mounted /dev/nvme0n1p1

How to reproduce it (minimal and precise):
Using ceph-helm with 
ceph/daemon:tag-stable-3.0-luminous-centos-7 on Kubernetes with an NVMe disk attached to the host.

**Environment**:
* OS (e.g. from /etc/os-release): Amazon Linux 2
* Kernel (e.g. `uname -a`): 4.14.72-73.55.amzn2.x86_64
* Docker version (e.g. `docker version`): 17.06.2-ce
* Ceph version (e.g. `ceph -v`) :12.2.4 (52085d5249a80c5f5121a76d6288429f35e4e77b) luminous (stable)

It looks like this issue lies in https://github.com/ceph/ceph-container/blob/master/src/daemon/common_functions.sh#L135, which doesn't seem to have a special case for nvme devices.

**Comment by lty1993** [comment]
I have the same problem while using nvme ssd.

**Comment by hex43ver** [comment]
I have a similar issue, my case is likely caused by one line issue when scan legacy partitions:

https://github.com/ceph/ceph-container/blob/master/src/daemon/osd_scenarios/osd_disk_activate.sh#L25

And previously other place like osd_volume_activate.sh has different way to scan partitions for nvme device:

      if [[ "${device}" =~ ^/dev/(cciss|nvme|loop) ]]; then
        device+="p"
      fi

In latest change d07436a353f499f11b2ce65c50686702083f8881 @dsavineau used a new approach to scan the data partition, likely osd_disk_activate.sh should also make similar change.
