### ISSUE TITLE
smartctl and nvme tools missing from container

### ISSUE THREAD

**Issue by KingJ** [ceph/ceph-container#1396]
Is this a bug report or feature request?
* Feature Request

Currently, the ceph-container image used by OSDs is missing the `smartctl` (>=7.0) and `nvme` CLI utilities. These utilities are used by the new Device Monitoring feature in Nautilus to capture metrics about the health of the OSD's underlying physical device. Without these utilities, metrics cannot be automatically gathered, preventing the health prediction function from working.

Are there any similar features already existing:
Possibly - [Ceph blog post on Nautilus's new Health Metrics feature](https://ceph.com/update/new-in-nautilus-device-management-and-failure-prediction/) mentions that "pieces should fall into place soon", however I have not been able to find any related issues, commits or PRs on the ceph-container Github project or Ceph issue tracker. (apologies if this is being tracked somewhere and this issue is superfluous as a result!).

What should the feature do:
`smartctl` (>=7.0) and `nvme` CLI utilities should be present in the Ceph Container image used by OSDs.

What would be solved through this feature:
Containerised Ceph OSDs would be able to collect Health Metrics about the underlying physical device, enabling device failure predictions.

Does this have an impact on existing features:
No

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
* Kernel (e.g. `uname -a`): 4.18.0-21-generic
* Docker version (e.g. `docker version`): 18.09.6
* Ceph version (e.g. `ceph -v`): ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)

**Comment by mykaul** [comment]
Would be nice to have them, if possible, in a separate container, as I assume they are quite privileged, whereas the rest of the OSD code can be further constrained.

**Comment by dsavineau** [comment]
The current images present on dockerhub are based on CentOS 7 which doesn't have a recent enough smartctl release (6.5). The CentOS 8 release will only have 6.6 too.
There's a smartmontools build available via the centos 7 nautilus repository (centos-release-ceph-nautilus [1]) but we are using the ceph bits from [2] so we might have some ceph packages conflict. I will give it a try.
For the nvme cli it doesn't seems to be an issue.

I don't think those tools need to be in a separate container because the ceph process needs to call them so it needs to be in the same container. Also the OSD container needs to be executed with privileged.

[1] https://cbs.centos.org/koji/buildinfo?buildID=25069
[2] https://download.ceph.com/rpm-nautilus/el7/

**Comment by ktdreyer** [comment]
We're tracking smartmontools 7.0 for RHEL 8 here: https://bugzilla.redhat.com/show_bug.cgi?id=1671154

I'm happy to hear you are looking at this from the container side. Please let me know how I can help.

**Comment by dsavineau** [comment]
That's a great news ! Thanks for the tracking Ken.
