### ISSUE TITLE
ganesha.nfsd missing from arm64 docker image

### ISSUE THREAD

**Issue by croustiPoulet** [ceph/ceph-container#1397]
Is this a bug report or feature request?
* Bug Report

### **Bug Report**

**What happened:**
ganesha.nfsd missing from the arm64 docker image:
docker run ceph/ceph:v14.2.1-20190430 find | grep ganesha
38632:./usr/share/ceph/mgr/dashboard/services/ganesha.pyc
38659:./usr/share/ceph/mgr/dashboard/services/ganesha.py
38699:./usr/share/ceph/mgr/dashboard/controllers/nfsganesha.pyc
38719:./usr/share/ceph/mgr/dashboard/controllers/nfsganesha.py
38750:./usr/share/ceph/mgr/dashboard/tests/test_ganesha.py
38767:./usr/share/ceph/mgr/dashboard/tests/test_ganesha.pyc

Whereas on x86 machine:
docker run ceph/ceph:v14.2.1-20190430 find | grep -i ganesha
./run/ganesha
./usr/bin/ganesha.nfsd
./usr/bin/ganesha-rados-grace
./usr/lib/tmpfiles.d/ganesha.conf
./usr/lib64/ganesha
./usr/lib64/ganesha/libfsalrgw.so
./usr/lib64/ganesha/libfsalceph.so.4.2.0
./usr/lib64/ganesha/libfsalceph.so.4
./usr/lib64/ganesha/libfsalceph.so
./usr/lib64/ganesha/libfsalrgw.so.4.2.0
./usr/lib64/ganesha/libfsalrgw.so.4
./usr/share/ceph/mgr/dashboard/controllers/nfsganesha.py
./usr/share/ceph/mgr/dashboard/controllers/nfsganesha.pyc
./usr/share/ceph/mgr/dashboard/services/ganesha.py
./usr/share/ceph/mgr/dashboard/services/ganesha.pyc
./usr/share/ceph/mgr/dashboard/tests/test_ganesha.py
./usr/share/ceph/mgr/dashboard/tests/test_ganesha.pyc
./usr/libexec/ganesha
./usr/libexec/ganesha/nfs-ganesha-config.sh
./etc/yum.repos.d/ganesha.repo
./etc/logrotate.d/ganesha
./etc/sysconfig/ganesha
./etc/dbus-1/system.d/org.ganesha.nfsd.conf
./etc/ganesha
./etc/ganesha/ganesha.conf
./etc/ganesha/ceph.conf
./etc/ganesha/rgw_bucket.conf
./etc/ganesha/rgw.conf

**What you expected to happen:**
ganesha.nfsd should be available in arm64 image just like on x86.
This prevents from exporting a ceph distributed filesystem through NFS with rook on arm64 cluster.

**How to reproduce it (minimal and precise):**
Pull the last nautilus ceph docker image on arm64 and check if ganesha.nfsd binary is there.

### **Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
* Kernel (e.g. `uname -a`):
Linux pc0 4.4.52-armada-17.10.1-gc645ecc #1 SMP PREEMPT Thu Jan 25 05:36:06 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
* Docker version (e.g. `docker version`):
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:40:48 2019
 OS/Arch:           linux/arm64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:00:10 2019
  OS/Arch:          linux/arm64
  Experimental:     false
* Ceph version (e.g. `ceph -v`):
ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)

**Comment by dsavineau** [comment]
unfortunately there's no arm64 build for nfs-ganesha. I don't know if it's something missing upstream or not (because the directory exists) either on v2.7 or v2.8

http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/nautilus/aarch64/
https://2.chacra.ceph.com/r/nfs-ganesha/next/39739212fe9e60bf30e13e5640af7c145e3a5592/centos/7/flavors/ceph_master/aarch64/

**Comment by XenGi** [comment]
This is still not fixed. I tried building release 4.0.10 on aarch64 and got the same error: https://gist.github.com/XenGi/0d806caaac390f79328824bfe368d6b6

**Comment by dsavineau** [comment]
@XenGi 

1/ That's not how to build the arm64 container image. Please see [1] otherwise you won't use the right centos directory [2] for this architecture.
2/ Even with if you build the arm64 container image (I don't understand why it's not present on docker.io [3] for v4.0.10), we explicitly disable nfs-ganesha for arm64 build because there's no build available at all. And that's not the a ceph-container problem.

[1] https://github.com/ceph/ceph-container/blob/master/contrib/build-push-ceph-container-imgs-arm64.sh#L26
[2] https://github.com/ceph/ceph-container/tree/master/ceph-releases/nautilus/centos-arm64
[3] https://hub.docker.com/repository/docker/ceph/daemon-base/tags?page=1&name=v4.0.10

**Comment by XenGi** [comment]
Thx alot that worked.
