### ISSUE TITLE
vulnerabilities found in  ceph/ceph:v14.2 docker image

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-container#1454]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

ceph-csi uses `ceph/ceph:v14.2` as the base image, there are around  34 `vulnerabilities` are found  in the ceph-csi image because of the base image
What you expected to happen:
update `ceph/ceph:v14.2` image to fix  vulnerabilities

How to reproduce it (minimal and precise):

build a new image from `ceph/ceph:v14.2` and push it to `quay.io`  you should be able to see issues
 [ceph-csi docker image](https://github.com/ceph/ceph-csi/blob/master/deploy/cephcsi/image/Dockerfile)
[vulnerabilities show in  quay.io](https://quay.io/repository/cephcsi/cephcsi/manifest/sha256:d013e189f9dfda9555729b2d7c1463975c335b98c1a4d11fc9b72ed530fed919?tab=vulnerabilities)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version (e.g. `docker version`):
* Ceph version (e.g. `ceph -v`):

**Comment by humblec** [comment]
@leseb

**Comment by leseb** [comment]
Just pasting the reply I sent to @humblec already:

> Unfortunately, the centos image doesn't have any updates and we are
already running the latest version.
Indeed there are vulnerability:
https://hub.docker.com/_/centos/scans/library/centos/latest
We just need to wait for an update, our job runs every day, once a new
version is available we will pick it up.

Since this issue will naturally be solved when the centos image gets updated I'm closing this, feel free to re-open of you have any more concerns.
