### ISSUE TITLE
Can not get ceph-iscsi.repo when specified BASEOS_TAG with luminous

### ISSUE THREAD

**Issue by ericxiett** [ceph/ceph-container#1562]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
When specified 'BASEOS_TAG', build image failed.

make FLAVORS="luminous-12.2.11,centos,7" RELEASE=12.2.11-1 TAG_REGISTRY=registry.icp.com:5000/library/ceph BASEOS_REGISTRY=registry.icp.com:5000/library/os BASEOS_REPO=inspur-centos-7 BASEOS_TAG=5.0.0 DAEMON_TAG=ceph:12.2.11-1 IMAGES_TO_BUILD=daemon DAEMON_BASE_TAG=ceph-base:12.2.11-1 build

can not get correct ceph-iscsi.repo cause that wrong url 'https://download.ceph.com/ceph-iscsi/2/rpm/el12.2.11-1/ceph-iscsi.repo'

What you expected to happen:
Url should be https://download.ceph.com/ceph-iscsi/2/rpm/el7/ceph-iscsi.repo

How to reproduce it (minimal and precise):
Specify BASEOS_TAG=5.0.0

**Environment**:
* OS (e.g. from /etc/os-release):
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Kernel (e.g. `uname -a`):
Linux xiett.novalocal 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Docker version (e.g. `docker version`):
Docker version 18.09.7, build 2d0083d
* Ceph version (e.g. `ceph -v`):
12.2.11

**Comment by dsavineau** [comment]
> What happened:
> When specified 'BASEOS_TAG', build image failed.
> 
> make FLAVORS="luminous-12.2.11,centos,7" RELEASE=12.2.11-1 TAG_REGISTRY=registry.icp.com:5000/library/ceph BASEOS_REGISTRY=registry.icp.com:5000/library/os BASEOS_REPO=inspur-centos-7 BASEOS_TAG=5.0.0 DAEMON_TAG=ceph:12.2.11-1 IMAGES_TO_BUILD=daemon DAEMON_BASE_TAG=ceph-base:12.2.11-1 build
> 
> can not get correct ceph-iscsi.repo cause that wrong url 'https://download.ceph.com/ceph-iscsi/2/rpm/el12.2.11-1/ceph-iscsi.repo'

Is this a typo ? because if you use `BASEOS_TAG=5.0.0` then it should generate https://download.ceph.com/ceph-iscsi/2/rpm/el5.0.0/ceph-iscsi.repo

> 
> What you expected to happen:
> Url should be https://download.ceph.com/ceph-iscsi/2/rpm/el7/ceph-iscsi.repo
> 
> How to reproduce it (minimal and precise):
> Specify BASEOS_TAG=5.0.0

Unfortunately we don't support other centos container base image than CentOS 7 and 8 (ie with customized BASEOS_TAG and BASEOS_REPO).
At some point it doesn't make sense to use FLAVORS="luminous-12.2.11,centos,7" (meaning CentOS 7) with `BASEOS_TAG=5.0.0` because it doesn't reflect the CentOS release anymore and break the current installation workflow

**Comment by ericxiett** [comment]
@dsavineau, sorry, it's a typo.

> Unfortunately we don't support other centos container base image than CentOS 7 and 8 (ie with customized BASEOS_TAG and BASEOS_REPO).
Get it. But i found that there are not el8 in  https://download.ceph.com/ceph-iscsi/2/rpm/. How can we resolve this?

**Comment by dsavineau** [comment]
> Get it. But i found that there are not el8 in https://download.ceph.com/ceph-iscsi/2/rpm/. How can we resolve this?

You can't. There's no el8 build for ceph-iscsi on https://download.ceph.com/
The only one ceph release that is compatible with el8 which is octopus (current master ceph branch and unreleased) so stable release like luminous, mimic or nautilus are only supported on el7.
The octopus build is using devel repository for ceph-iscsi on https://shaman.ceph.com/ (which is based on el8).

You can have more information via [1]

Just to understand, what are you trying to achieve ?
Because there's a strict ceph-iscsi matrix depending on the ceph release.

- luminous : ceph-iscsi 2.x on el7
- mimic : ceph-iscsi 2.x on el7
- nautilus : ceph-iscsi 3.x on el7
- octopus : ceph-iscsi 3.x on el8

[1] https://github.com/ceph/ceph-container/blob/master/ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__#L22-L30

**Comment by ericxiett** [comment]
Should we add judgment to el7 and el8 in the judgment logic?
Like:
If el7, use url https://download.ceph.com/.
If el8, use url of shaman.

**Comment by dsavineau** [comment]
> Should we add judgment to el7 and el8 in the judgment logic?
> Like:
> If el7, use url https://download.ceph.com/.
> If el8, use url of shaman.

While this is true ATM this won't be true when octopus will be released.
