### ISSUE TITLE
 How to support the modification of lvm.conf

### ISSUE THREAD

**Issue by yanest** [ceph/ceph-container#1813]
I use the ceph octopus cluster installed by cephadm, and I use open-cas-linux to cache osd, so I need to modify the lvm.conf file to enable lvm support. Otherwise, using ceph orch daemon add osd ceph1:/dev/cas1-1 will report an error: "Device /dev/cas1-1 excluded by a filter". I have modified the lvm.conf on the server, but it is located in the container. How to deal with this problem?

**Comment by dsavineau** [comment]
That's not related to ceph-container directly but to the ceph orchestrator (cephadm) which consumes the ceph containers.

cephadm doesn't bind mount the lvm configuration from the host to the osd containers so that could be the reason why you have such issue.

I would recommend to open an issue on the ceph tracker instead as there's nothing to do on the container side.

https://tracker.ceph.com/projects/orchestrator/issues
