### ISSUE TITLE
Newbie question about import/export

### ISSUE THREAD

**Issue by aga20** [ceph/ceph-container#183]
Hello all!

So this is just a question but maybe you can help me. The situation is same: we use your solution as a docker registry backend. I try to find in the last month tool or solution how can I migrate our test "database" to the production "database". I found only just one tool, rados import/export for example here http://cephnotes.ksperis.com/blog/2015/04/15/ceph-pool-migration but whe I try to use it I got this message: "The import and export operations are not available". have you got any idead how can I solve this problem? 

Thanks for your help!

**Comment by leseb** [comment]
Can you share a log?

**Comment by nyov** [comment]
They disabled the `rados import/export` feature. http://tracker.ceph.com/issues/9403
Only just noticed myself *after* upgrading the cluster. Holy sheeeeeeeet.
Now I know why I didn't trust this thing. Way too late...

**Comment by ktdreyer** [comment]
@dzafman , the above comment mentions that Redmine issue 9403 is closed. What is the replacement there?

**Comment by nyov** [comment]
According to [this patch](http://lists.ceph.com/pipermail/ceph-commit-ceph.com/2015-May/001843.html) at https://github.com/ceph/ceph/commit/402b7b385f2adbe2befbb0edadcc9632832dc718, it's been (or will be) dropped without replacement:
```
commit 402b7b385f2adbe2befbb0edadcc9632832dc718
Author: John Spray <john.spray at redhat.com>
Date:   Fri May 29 14:19:16 2015 +0100

    tools/rados: rename dump/undump to export/import
    
    Since the old ones were disabled anyway, it should not
    upset anyone to steal their names.
    
    Signed-off-by: John Spray <john.spray at redhat.com>
```

So I suppose from now on it's DIY, to build an exporter using librados.
I would love to be wrong here, though.

**Comment by dzafman** [comment]
@nyov The new export/import works better than the older export/import because it preserve all the state of the objects.  It builds a single file containing all of the information to import.  Like the older version it doesn't save any snapshots.  The original export/import code had become broken because it wasn't updated with various changes in Ceph.  Also, it tried to save each object as named file in whatever Linux fs was specified.  Someone could write a script to read all the objects in a pool and create a file for each object somewhere.  If needed, the script could read xattrs and omaps and save that information in a parallel fie to the object data.  If needed, the script could handle namespaces by creating directories to store objects in non-default namespaces.

Maybe an export consisting of obj1, obj2, ns1/obj1, ns1/obj2, ns2/obj1, ns2/obj2:
export
export/attrs
export/attrs/ns1
export/attrs/ns1/obj1
export/attrs/ns1/obj2
export/attrs/ns2
export/attrs/ns2/obj1
export/attrs/ns2/obj2
export/attrs/--default
export/attrs/--default/obj1
export/attrs/--default/obj2
export/omaps
export/omaps/ns1
export/omaps/ns1/obj1
export/omaps/ns1/obj2
export/omaps/ns2
export/omaps/ns2/obj1
export/omaps/ns2/obj2
export/omaps/--default
export/omaps/--default/obj1
export/omaps/--default/obj2
export/data
export/data/ns1
export/data/ns1/obj1
export/data/ns1/obj2
export/data/ns2
export/data/ns2/obj1
export/data/ns2/obj2
export/data/--default
export/data/--default/obj1
export/data/--default/obj2

**Comment by dzafman** [comment]
@nyov You'd have to update to a Jewel release to get the new rados export/import as I describe above.  If you know how to build Ceph yourself you could re-enable the old export/import in src/tools/rados/rados.cc.  Do so at your own risk and test thoroughly before using in production.

diff --git a/src/tools/rados/rados.cc b/src/tools/rados/rados.cc
index 01152df..3785052 100644
--- a/src/tools/rados/rados.cc
+++ b/src/tools/rados/rados.cc
@@ -2725,9 +2725,7 @@ int main(int argc, const char **argv)
     return 1;
   }
   if ((strcmp(args[0], "import") == 0) || (strcmp(args[0], "export") == 0)) {
-    cout << "The import and export operations are not available" << std::endl;
-    exit(1);
-    //return rados_tool_sync(opts, args);
+    return rados_tool_sync(opts, args);
   } else {
     return rados_tool_common(opts, args);
   }

**Comment by nyov** [comment]
As I only need to get files out of the cluster, with no re-import, I went with the second solution here of recompiling my rados binary.
It seems to work for me (on 0.94.9 Hammer), but I'll consider writing me a python-rados replacement in the future.

@dzafman, thanks for letting me know that this piece of code still works when reenabled. I feared it might not work or have bad consequences if I did that hack, before your post.
(A `--yes-i-know-this-is-deprecated` flag would have been a much nicer solution instead.)

I will consider upgrading to Jewel later, but since the upgrade docs are obviously incomplete and not mentioning such changes as this one, I will need to be very careful with it and set up some VM-based testing environment for that.
As I can't find any docs on this "new export" I wouldn't know how I can use it until I have a working deployment to try it out.
(That the [Jewel release docs](http://docs.ceph.com/docs/jewel/releases/) don't even know about a jewel release currently, is not very trust-inspiring. According to the page, right now, all current Ceph releases are retired. ;)

Finally, I also hope @aga20's question has been answered and this issue resolved. Sorry for butting in here. (I wish the ceph repo would allow GH Issues.)
