### ISSUE TITLE
Clarification of build/release versioning

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/ceph-container#1899]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

I'd like to request that the readme, or some related documentation, help explain the relationship between ceph/daemon & ceph/daemon-base - which are mentioned in the readme - vs. ceph/ceph, which doesn't appear to be. However, I note that ceph/ceph seems to get new ceph versions faster. This project doesn't create new release versions for every version of ceph and I don't really have complaints about that, but it is quite unclear to me when I can expect a matching version of ceph/daemon-base:latest-X (where X=octopus,pacific,etc).

This issue stems from the fact that the go-ceph project uses the daemon-base image for our ci. Frequently, when ceph issues a new release we experience CI failures because we need devel packages and those are pulled from ceph's repos. Unfortunately, those repos do not retain older versions and thus our ci breaks until the latest-X tag matches the latest ceph version.

I think it would be helpful for projects that consume these images, like go-ceph, to have a better understanding of what triggers new image builds and what kind of timings we should expect. Thanks!

**Comment by dsavineau** [comment]
Part of the answer is present in the ceph documentation [1]

But in short :

- ceph/ceph are stable images with ceph binaries and deps (but no devel packages).
Each time a new ceph release is out then a new container image is built automatically with the tag matching that release number (ceph pacific 16.2.4 == container image tag v16.2.4)
Any project based on ceph stable release (like go-ceph I assume) should use those images, not ceph/daemon-base. That's what cephadm and rook are doing.

- ceph/daemon-base is same content than ceph/ceph but the tag release is completly different.
You should use those images only for testing ceph@master because ceph/ceph only provides images for stable releases.
The container image tags are generated
  - each time a PR is merged on ceph/ceph-container : latest-master, latest-pacific, latest-octopus and latest-nautilus
  - each day for unreleased ceph content (fix present in a branch but not part of a stable release) : latest-master-devel, latest-pacific-devel, latest-octopus-devel and latest-nautilus-devel
  - each time a ceph-container release is made : v6.0.3-stable-6.0-pacific-centos-8, v5.0.11-stable-5.0-octopus-centos-8, v4.0.21-stable-4.0-nautilus-centos-7, etc... [2]

- ceph/daemon is based on top of ceph/daemon-base and adds some shell scripts for automation consume by ceph-ansible mainly (and probably in other usecases).
The container image tags are the same than ceph/daemon-base.

So if a new ceph release is out but there's no PR merged in the ceph-container project then you won't have the latest ceph content with the latest-xxx tags.
That's why I'll suggest you to use ceph/ceph instead.

[1] https://docs.ceph.com/en/latest/install/containers/
[2] https://github.com/ceph/ceph-container/releases

**Comment by phlogistonjohn** [comment]
Thanks! We'll look into checking that ceph/ceph works and if so make use of it.
I'll close this as the question has been answered and keep in touch on other channels if we have questions/requests on the use of ceph/ceph.
