### ISSUE TITLE
Swagger UI files missing in Dashboard since v6.0.6

### ISSUE THREAD

**Issue by tinol** [ceph/ceph-container#1977]
**Bug Report**

What happened: Opening the API documentation in the Dashboard on /docs only shows an empty page. swagger-ui-bundle.js and swagger-ui.css 404'd.

What you expected to happen: Seeing the Swagger UI.

swagger-ui-bundle.js and swagger-ui.css in /usr/share/ceph/mgr/dashboard/frontend/dist/en-US/ are missing in the the mgr container since the latest release. They were still there in v6.0.5.

**Environment**:
* OS (e.g. from /etc/os-release): Debian 11
* Kernel (e.g. `uname -a`): 5.10.0.10-cloud-amd64
* Docker version (e.g. `docker version`): 20.10.5+dfsg1
* Ceph version (e.g. `ceph -v`): 16.2.7

**Comment by dsavineau** [comment]
That's not a ceph-container issue but a change made in ceph dashboard. You will have the same issue using the ceph-mgr-dashboard package in v16.2.7

Since [1] the `swagger-ui-dist` npm module as been removed (dashboard uses `swagger-ui` instead) so both `swagger-ui-bundle.js` and `swagger-ui.css` files aren't present anymore.

If you still have some concern about the dashboard, I would recommend you to open an issue on the ceph tracker for the dashboard [2]

[1] https://github.com/ceph/ceph/commit/7ab8d3a636a7bda0c3f905ca5b6d0b336fe7d6a1
[2] https://tracker.ceph.com/projects/dashboard
