### ISSUE TITLE
kviator doesn't store/retrieve binary data safely

### ISSUE THREAD

**Issue by fmeppo** [ceph/ceph-container#220]
kviator is used to store a bunch of useful pieces in various KV stores - but it seems to only handle ascii files (at least, that's the case with the etcd version I'm using).  Keyrings are fine, but the monmap is a binary file.  config.kv.sh stores monmap via kviator, and a corrupt version will be retrieved later.  Looks like binaries like monmap must be uuencoded first (and uudecoded on extraction).

**Comment by Ulexus** [comment]
Wow, you're right.  kviator is using string values instead of byte slices.  (The underlying libkv does use byte slices, though, which should be binary safe.)  This is, indeed, a problem for binary storage like the monmap.

**Comment by fmeppo** [comment]
Yup.  See pull request #221 for a fix.  Tested on my local kit, and it seems to work (in that my replicated MONs are now coming up, using a monmap from etcd).

**Comment by CoRfr** [comment]
I think there is an issue with this patch for existing installations.
One of my monitors restarted an pulled this image, it was not able to use the existing monmap and therefore crashed, also leaving the configuration locked.

I'm seeing the following error:
```
Feb 18 17:46:44 carmd-ev-lxcim2 docker[9861]: 2016-02-18T17:46:44Z carmd-ev-lxcim2 confd[108]: INFO Target config /etc/ceph/ceph.conf out of sync
Feb 18 17:46:44 carmd-ev-lxcim2 docker[9861]: 2016-02-18T17:46:44Z carmd-ev-lxcim2 confd[108]: INFO Target config /etc/ceph/ceph.conf has been updated
Feb 18 17:46:44 carmd-ev-lxcim2 docker[9861]: Adding Keyrings
Feb 18 17:46:44 carmd-ev-lxcim2 docker[9861]: Monmap is missing. Adding initial monmap...
Feb 18 17:46:44 carmd-ev-lxcim2 docker[9861]: uudecode fatal error:
Feb 18 17:46:44 carmd-ev-lxcim2 systemd[1]: Stopped docker container f92bfe8222290811b4777abf0cfbee2b809251c75cc49459a3b25d96411fba76.
```

I think the monmap with this new format could potentially be stored elsewhere, like monmap.enc or something alike, and there should be some code for the transition.
Something like:
```
Get monmap.enc
- OK => uudecode => done
- Not OK => Get monmap => Convert monmap to monmap.enc => done
```

**Comment by CoRfr** [comment]
A workaround for now was to log exec on a running monitor and do
```
apt-get update
apt-get install sharutils
uuencode /etc/ceph/monmap - | kviator --kvstore=${KV_TYPE} --client=${KV_IP}:${KV_PORT} put /ceph-config/ceph/monmap -
```

The path of the monmap is the default one, to be replaced if you have a different setup.

**Comment by Ulexus** [comment]
@CoRfr I didn't consider the broken path concern because I figured there was no way this could be working, currently.  You make a good point, though, and we _should_ have considered the breaking change.  

I think it's probably too late to go back and correct it (since we would then break all of the _new_ installations), but your workaround should be fine.  Would you care to add it to the documentation?

**Comment by Ulexus** [comment]
We could check to see if the uudecode fails and, if so, use the raw value, but I think I would rather just have a manual patch for this transition.

**Comment by leseb** [comment]
Sorry for the issue. I believe it all boils down to https://github.com/ceph/ceph-docker/issues/204 again where we could have handled that if we would have used tags and fixed releases instead of living master. Will try to address that in a couple of weeks.

**Comment by tobilg** [comment]
Changing the Docker Hub config should only take a few minutes, so that only **verified** releases are pushed. I'm right now in a situation where my dockerized Ceph cluster went corrupt the second time due to the single use of `latest` tags.

IMHO, Ceph is great, but currently not really usable via Docker if those issues are not resolved. I really appreciate all the work done by the contributors of this project, but I don't understand why this issue is not tackled in a timely manner, because it de-facto affects already deployed clusters in a negative way.

Thanks!

**Comment by hunter** [comment]
FWIW we've (finally!) released a updated version of kviator that includes binary support - https://github.com/AcalephStorage/kviator/releases/tag/v0.0.7

Not sure if we want to update since it will break existing unencoded monmaps but its around if needed.

**Comment by leseb** [comment]
Yeah let's wait a bit :)
