### ISSUE TITLE
deploy test registry

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-container#444]
So that it can be consumed by jobs that create containers on the fly. See issue #443

**Comment by ktdreyer** [comment]
If we are going to host a registry for tests, here are some things I'd like to investigate:

* Let's use a real hostname (registry.ceph.com) and SSL certificate
* Investigate hosting with DreamCompute, maybe use DreamObjects as the backing store
* Use CentOS Extras' docker-distribution package, since that is stable and will receive security updates from Red Hat

**Comment by ktdreyer** [comment]
I've set up [Atomic Registry](http://docs.projectatomic.io/registry/latest/registry_quickstart/) in a test environment, and I'm working to set up a prod environment at registry.ceph.com.

**Comment by leseb** [comment]
@ktdreyer that's great, thanks!

**Comment by ktdreyer** [comment]
registry.ceph.com is in DNS today. Still working out the Letsencrypt HTTPS certs and system accounts.
