### ISSUE TITLE
Cluster IP: None ?

### ISSUE THREAD

**Issue by qrpike** [ceph/ceph-container#518]
I noticed in the kubernetes example the ceph-mon service has the following
```yaml
clusterIP: None
```

I am curious what the point and reason for this is? I would like to set it to a static IP for inside of my cluster so I can reference it elsewhere. Is there any harm in setting it to a static ip?

Thanks

**Comment by bzub** [comment]
That setting creates SRV records in kube-dns that could potentially be used by software to dynamically identify the individual monitor IPs and ports.  With most ceph software if you try to use an IP different than what the monitor is actually bound to, like a service IP, it will throw an error because of the mismatch.

https://kubernetes.io/docs/user-guide/services/#headless-services

http://docs.ceph.com/docs/master/rados/configuration/mon-lookup-dns/

**Comment by hunter** [comment]
@qrpike if you need a static IP, I'd suggest adding `hostNetwork: true` to the ceph-mon spec, that will expose the mon directly on the host. You'll likely also need to constrain the mons to specific nodes to make sure they get scheduled to the corresponding nodes after any outages.
