### ISSUE TITLE
ceph/daemon mon with KV backend errors with multiple keys missing after populate

### ISSUE THREAD

**Issue by Riptawr** [ceph/ceph-container#888]
Hi all,

following the [setup docs for luminous on ubuntu 16](https://github.com/ceph/ceph-container/tree/master/ceph-releases/luminous/ubuntu/16.04/daemon) using both the default and a custom ceph.defaults the mon gets stuck on following keys:
```/ceph-config/<clustername>/client_host``` - fixed by manually passing setting it to the hostname via etcdctl
```/ceph-config/<clustername>/lock``` - key missing, fixed by creating and deleting it via etcdctl as well, after which the the mon entrypoint did un-stuck.

I skimmed through the bash-fu related to populate_kv.sh and entrypoint.sh.in, but couldn't figure out the call graph so i am submitting it as an issue for now. 

Are you considering PRs replacing the bash with a readable language at some point? Something i would be interested in contributing. As far as i can tell, Dockerfiles are using base images with at least Python available.

Regards,
LXK

**Comment by mangobowl** [comment]
same problem on the latest `ceph/daemon:tag-build-master-jewel-ubuntu-16.04` image

**Comment by leseb** [comment]
@mangobowl just triggered 2 news builds, this should be fixed soon.

**Comment by Riptawr** [comment]
@leseb @mangobowl 

tested with ceph/daemon:latest just now, lock issue is fixed, client_host still missing though
```
2018-02-06 09:52:59  /entrypoint.sh: 'auth' key already exists
2018-02-06 09:53:00  /entrypoint.sh: 'global' key already exists
2018-02-06 09:53:00  /entrypoint.sh: 'osd' key already exists
2018-02-06 09:53:00  /entrypoint.sh: Adding Mon Host - prgsupcmp01.
172.24.44.13
prgsupcmp01
Error:  100: Key not found (/ceph-config/ceph/monSetupComplete) [266]
2018-02-06 09:53:01  /entrypoint.sh: No configuration found for cluster ceph. Generating.
0f586fd8-1bbc-4d8f-b24c-77867edaa441
2018-02-06T09:53:01Z prgsupcmp01 /tmp/tmp.fTdSvQOmfr/confd[279]: INFO Backend set to etcd
2018-02-06T09:53:01Z prgsupcmp01 /tmp/tmp.fTdSvQOmfr/confd[279]: INFO Starting confd
2018-02-06T09:53:01Z prgsupcmp01 /tmp/tmp.fTdSvQOmfr/confd[279]: INFO Backend nodes set to http://172.24.44.13:2379
2018-02-06T09:53:01Z prgsupcmp01 /tmp/tmp.fTdSvQOmfr/confd[279]: ERROR 100: Key not found (/ceph-config/ceph/client_host
```

**Comment by mangobowl** [comment]
@Riptawr @leseb  I also tried the `tag-build-master-jewel-ubuntu-16.04` image just now, the same error as above.

**Comment by Raboo** [comment]
I've hit the same problem when upgrading from jewel to luminous (tag-stable-3.0-luminous-ubuntu-16.04)

I can create /ceph-config/<clustername>/client_host manually, but I don't know what content it should have..

**Comment by Raboo** [comment]
Ok, I don't know is this should be in a new issue or not.

I started with the `/ceph-config/<clustername>/client_host` problem.
Fixed it by creating a directory called client_host in etcd.

Got `Error:  105: Key already exists (/ceph-config/ceph/lock) [262]` loop problem after that on `tag-stable-3.0-luminous-ubuntu-16.04` and `tag-stable-3.0-luminous-centos-7`
Got past this problem by switching to `tag-build-master-luminous-ubuntu-16.04`.

But since I've upgraded from jewel apparently I don't have a `bootstrapRbdKeyring`.
Currently getting `Error:  100: Key not found (/ceph-config/ceph/bootstrapRbdKeyring) [267]`

Q: How should I manually create a bootstrap the RBD Keyring?

@leseb This (not this exact problem) happens every time I want to upgrade ceph-container.
1. trial and error over which docker images work best, they differ.
2. get stuck with some error since we don't deploy a new cluster, we are upgrading and upgrade lacks "adding new settings" that new setup does.

I need help 😞
