### ISSUE TITLE
etcd config improvements

### ISSUE THREAD

**Issue by ro0p** [ceph/ceph-container#915]
First, thank you for great work.

We use etcd cluster to store system wide configurations in our environments. It would be very helpful if ceph config can be easily integrated into existing environments.

It would be great if key-value store can be configured in "endpoints" way.
Currently KV_IP and KV_PORT only allows to define only one node, but it is not always enough if using etcd cluster.
For ex KV_ENDPOINTS="http://node1:port,http://node2:port,..." would be very useful. If https is given instead of http, KV_CA_CERT, KV_CLIENT_CERT and KV_CLIENT_KEY should be required.

Another great improvement can be if the hard coded "ceph-config" prefix can be configurable in the CLUSTER_PATH, and if it can accepts a path. For ex "< company >/< dc1 >/< cluster2 >/ceph" etc.

Thank you.

**Comment by leseb** [comment]
@ro0p thanks for your interest in the etcd store config but since Ceph (as of Mimic) will implement something similar in its core we won't work on that part of the code anymore.
I'm even thinking of deprecated this for Mimic and then drop it for the N release.

If there is anything you want now, you'll have to add yourself (sorry), but please consider the above by thinking on a transition plan.
