### ISSUE TITLE
request for iscsi gateway container

### ISSUE THREAD

**Issue by ro0p** [ceph/ceph-container#916]
There are some use cases when rbd images can be accessed only via old iscsi.
Is it planned to support iscsi gateway?

Thank you.

**Comment by leseb** [comment]
That's on-going, hopefully, next month.
Thanks!

**Comment by ro0p** [comment]
Great news! Thank you.

**Comment by betonmoewe** [comment]
hi,

are there any news about the iscsi_gateway? I have seen some scripts within the image, but if I try to start with /entrypoint.sh rbd_target_gw I got an error about "rtslib_fb.utils.RTSLibError: Could not load module: configfs" maybee because I have not set any further parameter ...

But all in all, I love this project! Thanks a lot !
I have now a running ceph cluster with swarm! (except osd (privileged not possible))

**Comment by leseb** [comment]
Oops missed this one, this was closed by https://github.com/ceph/ceph-container/pull/977

**Comment by leseb** [comment]
@betonmoewe containers must be privileged.
