### ISSUE TITLE
ceph-disk notes

### ISSUE THREAD

**Issue by hookenz** [ceph/ceph-container#98]
I'm really wanting that fully automated life cycle goal that the non-docker version as far as I can tell have.

So, toward that goal I just wanted somewhere to capture some `ceph-disk` notes and get peoples comments.  Sorry if this is a bit long winded.  I wish github had a discussion type of system.  Anyway, onwards...

Right now we're able to use, `ceph-disk prepare` as a step toward getting a ceph osd up.
I use it, because I run alongside my OSD spinning disks, 2 SSD's for journalling.

I prepare my OSD's like this:

```
docker run --rm --net=host --privileged=true -v /etc/ceph:/etc/ceph -v /dev:/dev ceph/base ceph-disk prepare --cluster ceph --cluster-uuid 683f638b-e2d1-40c2-969f-907d961a7d24 --fs-type xfs /dev/sda /dev/sde
```

Assuming my cluster-uuid is that above (gotten from my `ceph.conf`) and `/dev/sda` is my main data disk, `/dev/sde` is my journal disk.

Very conveniently, if I run the command again with a different data disk, and then use the same journal disk, `ceph-disk` will create another journal partition.  In actual fact, it creates a symbolic link to the journal disk on the main osd data disk.

Where everything falls over, is with `ceph-disk activate`.  It's just not going to work actually.  The reason it's not going to work is because it expects:
1. to be running natively (not docker).  
2. it auto-detects what OS you're using and what init system it is.  It's most likely going to get that totally wrong.  And besides that, the init system used in our images is not on the list.
3. `ceph-disk activate` also writes the OSD ID to the whoami file so you could move the disk elsewhere in future.

So, either ceph-disk would need to be changed to be docker aware (which would likely be very tied to this implementation), or we override it.  Or jump through hoops. Or use systemd inside the image... not sure I like that idea but I've heard it's possible.

`ceph-disk` code is here.  It's really just a python script that uses sgdisk, blkid and a few other tools to get the job done.  
https://github.com/ceph/ceph/blob/master/src/ceph-disk

I think the override idea is the easiest. 
As `ceph-disk activate` doesn't work, what I do is currently:
Assuming my OSD is /dev/sda & is osd 10

```
sudo mkdir -p /osd/tmp
sudo mount /dev/sda1 /osd/tmp
sudo echo 10 | tee /osd/tmp/whoami
sudo umount /osd/tmp
```

Which just writes the whoami file.   And combine that with my [mount-osds](https://github.com/ceph/ceph-docker/blob/master/examples/common/mount-osds) script.
If the disks ever need to be moved to another machine, then knowing in advance what disk is becomes a bit tedious.  This is where I think my mount-osds is really useful..  It'll mount them to /osd/ceph-$id.   It's not really entirely cluster aware but could be made to be.  i.e. currently semi-hardcoded to a cluster named ceph.  It's actually doing a bit of what ceph-disk does but does it in shell script so it can be run natively from CoreOS without requiring python and can run outside a container.

What I do is mount the disks by calling mount-osds before the docker ceph-osd container is started.
Or just calling it as an ExecStartPre= from a systemd service file or similar.

What I am thinking is merging some of this functionality with my ceph-tools scripts.  Override ceph-disk activate to actually do the above and the bits from the bootstrap-osd, then write a startup file to /etc/service/ceph-osd/run and start it with sv start.  

I'm not sure if this makes a terrible lot of sense to people yet... later I'll whip up an implementation and you can have a peek.  But I'd like to see @leseb daemon changes merged to make it work off that.  Anyway, those are my thoughts currently.

Would love to know how to add into systemd to call some custom udev rules, e.g. like if a ceph osd disk were moved it could run through a setup or restart process automagically.  Has anyone actually done that here?

**Comment by hookenz** [comment]
Just reading from https://github.com/ceph/ceph-docker/issues/81#event-331204412
Were you proposing using ceph-disk inside the ceph-osd or ceph-daemon image?
i.e. to actually mount osds as well which requires --privileged.

I was thinking you could maybe use a ceph-tools container that is started only to run ceph-disk privileged to do formatting.  Outside of that, ceph-disk is not used and instead we bootstrap the normal way.  This gets around the need for privileged.

In fact you may be able to remove --privileged and use --cap-add SYS_ADMIN and  SYS_RAWIO

**Comment by Ulexus** [comment]
@hookenz You describe the primary reason I do not like `ceph-disk` and `ceph-deploy`.  They are horrifically complicated python scripts for what they do; their complications are mainly due to their distribution detection and a whole bunch of really unnecessary "help-you" stuff (like the init script modification).  That self-same detection also renders them useless in the realm of containers.  All of that makes using them difficult and integrating with them a moving target.  This is why I strongly prefer, for the containers, to build from the basic binary tools and manual procedures.

I do think lifecycle management is really important.  There is the other discussion, #126 , which discusses the lifecycle management of the monitor.  Here is a good place for discussion of OSD lifecycle management, I think.

## Separation of duties

I've been irritated, recently, by our indistinction between the execution of the daemon and the bootstrapping and creation of the osd.  It is _easy_ to have them combined, and to have the container be "smart" about detecting and bootstrapping as necessary, but it is both dangerous and complicated.  It leads to lower flexibility, overall.

I think, as such, we should take an example from `ceph-disk` and decompose the process a bit.  I don't think there is any problem with having, for instance, separate commands:
 * `ceph/daemon osd create /dev/sdX [/dev/sdY]`
 * `ceph/daemon osd mount /dev/sdX`
 * `ceph/daemon osd [exec] /dev/sdX`
 * `ceph/daemon osd destroy /dev/sdX`

This also allows us to separate out most `--privileged` operations from the long-running `exec`.

Argument could easily be made, here, that `exec` should not, in fact, take a device argument, but should simply operate as it currently does, starting daemons for each OSD found in its `/var/lib/ceph/osd/` directory.

## Disk preparation

Another thing I don't like about `ceph-disk`, but I think is probably a good compromise, is that it operates on raw disks, rather than filesystems.  Personally, I greatly prefer the flexibility of mounting and preparing my own filesystems, but for use in a containerized environment, it might be best to simply have the partitioning and filesystem creation bundled into the process.  I'm definitely of two minds in this area, and I would be interested to hear others' thoughts.

## Ephemeralization

Full ephemeralization, like as in the #126 discussion for monitors, is not viable or safe for OSDs.  However, since OSDs have their own internal state via their filesystems, I do think the containers themselves should be completely stateless.  For the most part, they are already, but I want to keep this concept at the fore of design decisions.  The more ephemeral we can be, the easier it will be to work with kubernetes and the like.

## Miscellany

More could be done with specific backends (such as the key-value store), with creation, destruction, mounting, and execution, which could reduce external input and host-side/execution complexity.  In particular, referencing the machine id and its attached OSDs in the key-value store could make the actual execution of OSDs a simply matter of starting, without any additional contextual data (beyond the machineid).

**Comment by hunter** [comment]
Great comment @Ulexus. I've had similar thoughts regarding the OSDs. Although it would be nice to have a single OSD task that can flexibly handle multiple devices or dirs (bootstrap and exec), it may be easier (and more secure) to split the creation/prep off as you suggest.

**Comment by hookenz** [comment]
@Ulexus - I agree.  Maybe we should write our own ceph-disk style utility.

I know you hate using raw devices, but I prefer it for journals.  It bypass the filesystem layer for journalling.  And in some ways, at least the way I was using it I think it is easier to set up.  But then I could be swayed either way.  :)
