### ISSUE TITLE
Switching 'latest' from Ubuntu to CentOS

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-container#984]
Dear contributors,

 ,@foreverhex ,@tombarron ,@wedged ,@Riptawr ,@bassam ,@jprovaznik ,@prymitive ,@kpcyrd ,@zmc ,@dmick ,@djgalloway ,@xakep139 ,@dmonakhov ,@mgibula ,@bzub ,@galindro ,@ibotty ,@jimcurtis ,@sajal ,@jayconroy ,@alanmeadows ,@ganeshmaharaj ,@coffeepac ,@linuxwind ,@mgilham ,@danielin917 ,@dang ,@clinta ,@ivotron ,@mainboy ,@a-nldisr ,@bnoon ,@mbessler ,@walkerlee ,@xingjiudong ,@nickjanus ,@pokoli ,@onyiny-ang ,@theanalyst ,@rjfd ,@minshenglin ,@tobilg ,@nazar-pc ,@rochaporto ,@tobegit3hub ,@BugRoger ,@JrCs ,@qrpike ,@adamwg ,@AlessandroLorenzi 

This is an issue to announce that we are planning on using CentOS instead of Ubuntu as a base image for the `latest` tag. This does not mean we won't provide Ubuntu base container images anymore. We will keep on building them.

For those who are currently running on latest (so Ubuntu), you should either:

* stop using latest and pin on specific tags (see the [list](https://hub.docker.com/r/ceph/daemon/tags/) of tags) so you can keep on using Ubuntu
* transition to CentOS to keep using latest

For the transition, there are a couple of things to consider:

* changing ceph user id ([steps that can help](https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml#L92-L119))

* leveldb files extensions ([steps that can help](https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml#L232-L260))

Does anyone have any concern? If so, please raise them here.
We are planning on doing the switch by the end of next week.

Thanks in advance.

**Comment by leseb** [comment]
@ohmystack ,@xcompass ,@lorieri ,@hrchu ,@GregMeno ,@CoRfr ,@Raboo ,@mkkie ,@slang800 ,@yxwzaxns ,@untoreh ,@liewegas ,@ktdreyer ,@galexrt ,@ReSearchITEng ,@immesys ,@timn ,@deviantintegral ,@hookenz ,@TelanJ ,@elsonrodriguez ,@fmeppo ,@BertrandGouny ,@h0tbird ,@cornelius-keller ,@rootfs ,@streamnsight ,@font ,@dmitryint ,@guits ,@andrewschoen ,@alfredodeza ,@BlaineEXE ,@Ulexus ,@hunter ,@ErwanAliasr1

**Comment by Raboo** [comment]
Well my position is simple, we use containers to abstract away the OS. Should matter what distribution the container image is using. I'd preferably see images only based one OS.

**Comment by nazar-pc** [comment]
@Raboo, this is as long as you use it in out of the box state, but when you start customizing, suddenly underlying can make a difference.

**Comment by rootfs** [comment]
+1 one base OS, less is more

**Comment by leseb** [comment]
Just clarify, we are **not** dropping the support for multi-distro, we are just **switching** from Ubuntu to CentOS as our `latest` base OS image.

**Comment by timn** [comment]
We have been using the CentOS image exclusively for the past year (using a specific tag). That has worked nicely. We had chosen it mainly because all the remaining infrastructure also runs on CentOS. So I'm confident it's a good choice.

It might be worth considering [not to have a latest tag](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375) at all and require to choose a specific tag. This, however, is less about the OS but more about a ceph partial major version upgrade unknowingly (when 
just some nodes restart on the new image). A daily or development build with always the latest and brightest could have exactly such a nam, daily or development (similar to [Fedora rawhide](https://fedoraproject.org/wiki/Releases/Rawhide)).

**Comment by Raboo** [comment]
@timn makes a valid point, if you are switching OS base. Then you might just as well skip the latest tag altogether. Then it's really clear on what is what.

**Comment by leseb** [comment]
Sounds good, looks like this is not an issue. Let's wait and see if anyone has any concerns.
Thanks to those who responded so quickly!

**Comment by ganeshmaharaj** [comment]
Agree with @timn and the change should be fine.

**Comment by adamwg** [comment]
A little late to the party, but in the long term I'd be in favor of ceph-container supporting only a single base OS. When we've run into trouble with ceph-container in the past it's usually because something has changed in one OS version of the container and the changes either didn't make it to the OS we're using or didn't translate well. Supporting only a single base OS would make testing easier and eliminate the chance of losing parity between the different images.

**Comment by leseb** [comment]
@adamwg, sorry about the issues you experienced in the past. The new repo structure solves these kinds of problem.

**Comment by jamstar** [comment]
really late, but if your focused on one image, is there a reason you have not tried to go with alpine as that base image?  Ceph is the only part of my cluster that runs as a full os image.

**Comment by ErwanAliasr1** [comment]
@jamstar most of the upstream work is done by Redhat on this project, so it's easier for us to integrate our work into it. If anyone want to contribute an alpine based image, feel free to make a PR, I'd be happy to get a new maintainer & merge it.

**Comment by jamstar** [comment]
i use centos already for our cluster but was curious as to why.  

thanks for the info!
